### ISSUE TITLE
Maven Central

### ISSUE THREAD

**Issue by RobWin** [markdown-asciidoc/markdown-to-asciidoc#26]
Hello,

could you please sync the library to Maven Central via Bintray?

Kinds regards,

Robert Winkler

**Comment by bodiam** [comment]
I tried that, but I found the process too time consuming. Any reason why jcenter doesn't work?

**Comment by RobWin** [comment]
Hi,

some users of Swaggger2Markup forget to add JCentral to their repo list even if it is documented and they complain about it.
It would be easier for them if they can use Maven/Gradle default settings and just use Maven Central.

**Comment by bodiam** [comment]
In understand, and while I have nothing against doing that, it costs me too much time to figure out how to do it. I have no problem with it if you want to upload it, and if you need support, I can help.

**Comment by RobWin** [comment]
I can help you configure Gradle. The sync itself is done by Bintray automatically when you release a Version to JCentral). You just need to create a Sontaype account and register your groupId (Create a Jira Ticket). Thats it. Takes 10 minutes.
http://central.sonatype.org/pages/ossrh-guide.html

**Comment by RobWin** [comment]
Here is a short Tutorial
https://blog.bintray.com/2015/10/08/increase-your-maven-packages-exposure-by-adding-it-to-jcenter/

**Comment by matozoid** [comment]
I can testify that syncing to Maven Central through bintray is a relief. Once you have your group id registered (laamella.com in my case) you can just release any artifact that uses that group id. The best thing is that bintray does the signing stuff for you - you can tell it to sign everything with one of their keys and forget about it.

**Comment by guusdk** [comment]
Another argument for adding it to Maven Central: depending on any other than the sanctioned maven repository is a big no-no in some organisations.

**Comment by stianst** [comment]
Any updates on this? I would love to see this library in Maven Central.

**Comment by matozoid** [comment]
I think @bodiam would have done this if it was a priority for him, so I guess you will need to take action and do the release, @RobWin, @guusdk, or @stianst.

**Comment by bodiam** [comment]
It's not really a priority for me, but that doesn't mean I don't want to help. However, a step by step guide/gradle integration on how to do it would be nice, for I don't have the time at the moment to figure out the steps involved

**Comment by stianst** [comment]
@bodiam Do you even need guide/gradle integration? Seems like Bintray can sync the artifacts to Maven central for you and it won't make any changes to how you release the library once it's setup:
https://bintray.com/docs/usermanual/uploads/uploads_syncingwiththirdpartyplatforms.html

Seems like all you need is to create a Sontaype account and register your groupId, then setup the syncing in Bintray as @RobWin described previously.

It seems like this should take you 15 min to setup. I would have no issues with doing it for you, but I can't as I don't have access to your Bintray so you're really the only one that can do this.

**Comment by ASzc** [comment]
As a workaround for everyone blocked by this, I've published the artifacts for 1.0 under my namespace on Maven Central. To use those however, you'll need to exclude the dependency on the official groupId and add in a new dependency groupId. Here's an example pom snippet for using swagger2markup-maven-plugin:

```xml
<plugin>
    <groupId>io.github.swagger2markup</groupId>
    <artifactId>swagger2markup-maven-plugin</artifactId>
    <version>1.1.0</version>

    <!-- Replace the dependencies that aren't in Maven Central -->
    <dependencies>
        <dependency>
            <groupId>ca.szc.thirdparty.nl.jworks.markdown_to_asciidoc</groupId>
            <artifactId>markdown_to_asciidoc</artifactId>
            <!-- Keep in sync with markup-document-builder's dependency -->
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>io.github.swagger2markup</groupId>
            <artifactId>swagger2markup</artifactId>
            <!-- Keep in sync with swagger2markup-maven-plugin's dependency -->
            <version>1.1.0</version>
            <exclusions>
                <exclusion>
                    <groupId>nl.jworks.markdown_to_asciidoc</groupId>
                    <artifactId>markdown_to_asciidoc</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
    </dependencies>
</plugin>
```

**Comment by ahus1** [comment]
jcenter is about to shut down: https://www.infoq.com/news/2021/02/jfrog-jcenter-bintray-closure/

The one publishing the library needs to sign up a Sonatype for their namespace, and will later create GPG signatures. I know this is troublesome, I've been through this. 

There is a two-part blog post here covering both the signup, and the Gradle setup with a 4.x example. https://medium.com/@nmauti/sign-and-publish-on-maven-central-a-project-with-the-new-maven-publish-gradle-plugin-22a72a4bfd4b

@bodiam - is this the step-by-step guide you've been looking for? Unfortunately my working examples are Maven only. I'm willing to help when it comes to deciphering error messages with Sonatype.

**Comment by aalmiray** [comment]
@bodiam any luck on having a look to publish the latest bits to Maven Central? I could help with the setup 😏

**Comment by epragtbeamtree** [comment]
@aalmiray Hey Andres, it's quite low on my list of priority. I'm happy if you want to help!

**Comment by verhas** [comment]
Currently I am struggling to find the versions on jcenter as well on maven central.

I always publish on maven central, I do not see what the issue is, but okay... However, as of now JCenter is read only.

**Comment by dgautier** [comment]
@bodiam I created a ticket to release to maven central but i need you to create a repository so they validate the ownership of the repository. So can you create this : https://github.com/bodiam/OSSRH-93228 .

Thanks.

**Comment by bodiam** [comment]
@dgautier like this: https://github.com/bodiam/OSSRH-93228 ?

**Comment by dgautier** [comment]
@bodiam  To finalize publishing i need access to repository settings or maybe you can do it if youd' rather not give me those rights. I'm folowing up this : https://itnext.io/publishing-artifacts-to-maven-central-using-github-actions-a-step-by-step-guide-fd65ef075fd4
You'll need to create a sonatype account if you wanna do it.

Let me know about that.
Thanks,

**Comment by bodiam** [comment]
@dgautier I don't mind giving you access, but I can't find the controls to do it. See screenshot:

<img width="796" alt="image" src="https://github.com/bodiam/markdown-to-asciidoc/assets/46468/065076c5-2409-455d-a9d7-818552b95da5">

I do have a sonatype account, so I'm happy to arrange whatever you need.

**Comment by dgautier** [comment]
@bodiam Either you give me more rights on the project (not sure which rights is required in order to add variables) or you pick the tuto at the GPG setup Chapter

**Comment by guusdk** [comment]
(utterly off-topic, but kudos to anyone working on an issue that's 2.658 days old ;) )

**Comment by bodiam** [comment]
@dgautier apologies for the delay. I've moved this repo now to its own organisation, otherwise it's hard (impossible?) to give the right access control. Hope this will unblock you!

**Comment by dgautier** [comment]
@bodiam  it's better but i need to redo the publication process.  I created a ticket : https://issues.sonatype.org/browse/OSSRH-93793

And same as before you need to create a temp repository :  https://github.com/markdown-asciidoc/OSSRH-93793
(i don't have rights on https://github.com/markdown-asciidoc, only on https://github.com/markdown-asciidoc/markdown-asciidoc)

Let me know when it's done or if you gave me rights on https://github.com/markdown-asciidoc

Thanks

**Comment by bodiam** [comment]
Sorry for all of that. I've created the repo, I'll have a look to see how I can give you the proper rights!

**Comment by dgautier** [comment]
Finally published it : https://repo1.maven.org/maven2/io/github/markdown-asciidoc

**Comment by RobWin** [comment]
BAM :)

**Comment by bodiam** [comment]
That only took 8 years. Great job!

**Comment by verhas** [comment]
I have updated Jamal module that integrates into Asciidoctor IntelliJ plugin.

https://github.com/verhas/jamal/tree/master/jamal-asciidoc

**Comment by bodiam** [comment]
@dgautier I'd most likely want to publish a new version soon (I want to remove the Kotlin support, and maybe change the package name it's running under, so it's a bit of a breaking change, so most likely v3.0.0 or so). How can I publish a new version?

**Comment by dgautier** [comment]
@bodiam How can i contact you ? Comments on github aren't the easiest way to discuss.

**Comment by bodiam** [comment]
firstname.lastname at gmail !
