### ISSUE TITLE
Wrong coordinates in readme

### ISSUE THREAD

**Issue by Vampire** [markdown-asciidoc/markdown-to-asciidoc#59]
The readme tells to use `nl.jworks.markdown_to_asciidoc:markdown_to_asciidoc:2.0.0`, but it now is `io.github.markdown-asciidoc:markdown-to-asciidoc:2.0.0`.

**Comment by bodiam** [comment]
Fixed here: https://github.com/markdown-asciidoc/markdown-to-asciidoc/commit/bbe77dfb38a7bdfdf4f54c4a37cf84dcbc245e35
