### ISSUE TITLE
Source blocks sometimes get an extra blank line

### ISSUE THREAD

**Issue by Vampire** [markdown-asciidoc/markdown-to-asciidoc#66]
If you convert

    foo

    ```kotlin
    println("bar")
    ```

    baz

    ```kotlin
    println("bam")
    ```

the expected result is
```adoc
foo

[source,kotlin]
----
println("bar")
----

baz

[source,kotlin]
----
println("bam")
----
```

but what you get is
```adoc
foo

[source,kotlin]
----
println("bar")

----

baz

[source,kotlin]
----
println("bam")
----
```

If you remove the "foo" it works as expected,
if you remove the second code block it also works as expected,
if you remove the "baz" nothing changes, this is only there to not get the idea it is because directly following code blocks.
In the real document the second code block was way down in another section.

**Comment by bodiam** [comment]
Fixed here: https://github.com/markdown-asciidoc/markdown-to-asciidoc/pull/77
