### ISSUE TITLE
JDK17?

### ISSUE THREAD

**Issue by rdmueller** [markdown-asciidoc/markdown-to-asciidoc#88]
Does the build need JDK17 or can we lower the Java Version?

I currently update docToolchain with this version for the markdown-to-asciidoc library and this is the first library which not only needs JDK 14 but 17 which raises the bar...

**Comment by bodiam** [comment]
@rdmueller There's no great reason why this library is on Java 17, but Java 17 was released close to 3 years ago. Maybe it's time to upgrade? 

I don't even have Java 11 installed on my machines anymore.

**Comment by rdmueller** [comment]
yes, true. I already found a solution which disables the markdown functionality if used with a lower javaversion.
But you are right - we shouldn't use older versions anymore!
Thanx for your quick feedback

**Comment by bodiam** [comment]
Hi @rdmueller , I just had a look at docToolchain, but it seems it's built using a build matrix supporting 11, 14 and 17. Why not change that to 17, 21 and 22? (we do the same for Datafaker)

**Comment by rdmueller** [comment]
yes, I guess this will be the next step :-)
but first I have to fix and replace some outdated dependencies...

**Comment by rdmueller** [comment]
adding 21 was a good idea - tests fail :-D
